import { Spacing } from '@/theme/spacing';
import type { HeroBanner, HeroSlide } from '@/types/homepage.types';
import { Image } from 'expo-image';
import { router } from 'expo-router';
import { useMemo, useState } from 'react';
import type { ImageSourcePropType } from 'react-native';
import { StyleSheet, useWindowDimensions, View } from 'react-native';
import { FrostedCard } from '../layout/FrostedCard';
import { Button } from '../ui/Button';
import { ImageCarousel } from '../ui/ImageCarousel';
import { Skeleton } from '../ui/Skeleton';
import { Text } from '../ui/Text';

interface Props {
  banners: HeroBanner[];
  isLoading?: boolean;
}

// Shown when /homepage returns no usable hero imagery. The web client does the
// same (its API-driven slides are disabled behind a TODO and it renders only this
// fallback), so an empty heroSection must never leave the homepage headless.
//
// The artwork is generated by scripts/generate-app-assets.js as a bottom-anchored
// crop of hero-banner.png into the hero's own aspect ratio: the eyewear stays in
// frame and the backdrop's dark left half is left clear for the caption.
const FALLBACK_IMAGE: ImageSourcePropType = require('../../../../assets/images/hero-fallback.png');
const FALLBACK_TITLE = 'Great Collections';
const FALLBACK_DESCRIPTION = "The world's finest in premium eyewear";

// The API nests images inside banners; the slider wants one flat, ordered list.
export function buildHeroSlides(heroSection: HeroBanner[]): HeroSlide[] {
  const slides: HeroSlide[] = [];
  for (const banner of heroSection) {
    for (const doc of banner.documents ?? []) {
      if (!doc.imageUrl) continue;
      slides.push({
        documentId: doc.documentId,
        imageUrl: doc.imageUrl,
        isPrimary: doc.isPrimary,
        displayOrder: doc.displayOrder,
        title: banner.title,
        description: banner.description,
      });
    }
  }
  return slides.sort((a, b) =>
    a.isPrimary !== b.isPrimary ? (a.isPrimary ? -1 : 1) : a.displayOrder - b.displayOrder,
  );
}

function HeroOverlay({
  title,
  description,
  narrow = false,
}: {
  title?: string | null;
  description?: string | null;
  // The bundled slide has a known composition, so its caption is kept off the
  // product. API slides can be anything, so those keep the full-width chip.
  narrow?: boolean;
}) {
  if (!title && !description) return null;

  return (
    <View style={styles.overlay} pointerEvents="box-none">
      <FrostedCard tone="dark" style={narrow && styles.narrowCard}>
        {Boolean(title) && (
          <Text variant="bodySmall" tone="inverseMuted">
            {title}
          </Text>
        )}
        {Boolean(description) && (
          <Text variant="sectionHeadingOnDark" tone="inverseMuted" numberOfLines={3}>
            {description}
          </Text>
        )}
        <Button
          label="Shop now"
          variant="light"
          size="sm"
          onPress={() => router.push('/(customer)/(tabs)/explore')}
          style={styles.cta}
        />
      </FrostedCard>
    </View>
  );
}

export function HeroSlider({ banners, isLoading = false }: Props) {
  const { width } = useWindowDimensions();
  const [index, setIndex] = useState(0);
  const slides = useMemo(() => buildHeroSlides(banners), [banners]);
  // Figma: 205pt tall in a 428pt frame. Kept as a ratio so it scales across devices.
  const height = Math.round(width * (205 / 428));

  if (isLoading) return <Skeleton width={width} height={height} />;

  // A single bundled slide needs no carousel, and keeps ImageCarousel's remote-URL
  // contract intact.
  if (slides.length === 0) {
    return (
      <View style={{ width, height }}>
        <Image
          source={FALLBACK_IMAGE}
          style={{ width, height }}
          contentFit="cover"
          transition={200}
        />
        <HeroOverlay title={FALLBACK_TITLE} description={FALLBACK_DESCRIPTION} narrow />
      </View>
    );
  }

  const active = slides[index];

  return (
    <View>
      <ImageCarousel
        images={slides.map(s => s.imageUrl)}
        width={width}
        height={height}
        showDots
        onIndexChange={setIndex}
        renderOverlay={() => (
          <HeroOverlay title={active?.title} description={active?.description} />
        )}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  overlay: {
    ...StyleSheet.absoluteFill,
    justifyContent: 'flex-end',
    padding: Spacing[2],
    marginTop: Spacing[10],
    // paddingBottom: Spacing[12],
  },
  // The eyewear occupies the right ~45% of the bundled artwork.
  narrowCard: { maxWidth: '76%' },
  cta: { alignSelf: 'flex-start', marginTop: Spacing[2], borderRadius: 4 },
});
